#define PERSIST_WAKEUP    0
#define PERSIST_DURATION  1

#define PERSIST_TEMP_UNIT   9
#define PERSIST_TEA_BLACK   10
#define PERSIST_TEA_GREEN   11
#define PERSIST_TEA_HERBAL  12
#define PERSIST_TEA_MATE    13
#define PERSIST_TEA_OOLONG  14
#define PERSIST_TEA_PUERH   15
#define PERSIST_TEA_ROOIBOS 16
#define PERSIST_TEA_WHITE   17